### ISSUE TITLE
Questions about general usage

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap/go-randgen#21]
Hi I'm interested in using this tool for my implementation. I have several questions:
我希望可以基于此工具开发我的软件。我有几个问题想要请教：

1.  How automatic is this tool? Could it run without any given 'zz' or 'yy' file?
在不给定 zz 或者 yy 文件的情况下，这个工具能够自动生成语句吗？

2. Is this tool compatible with other DBMSs such as MySQL, SQLite or PostgreSQL?
此工具是否兼容其他的数据库系统，比如 MySQL？

Thank you :)  十分感谢

**Comment by DQinYuan** [comment]
1. It has a built-in zz , but yy is completely user-defined

2. If you only want to generate sql, yy has nothing to do with concrete database. But if you want to use `go-randgen` to compare two dsn, it now only supports mysql (TiDB is compatible with MySQL).
