### ISSUE TITLE
Test failed `gendata/generators/letter.go:7:`

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap/go-randgen#30]
Run the following

````
$ cd go-randgen && make all
````

Test failed
````
gendata/generators/letter.go:7: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
````

Version
````
ubuntu@VM-0-15-ubuntu:~/go-randgen$ go version
go version go1.15 linux/amd64
````

**Comment by cyliu0** [comment]
I can't reproduce this on my Mac and CentOS with go1.14. Do you still hit this issue?

**Comment by zhangysh1995** [comment]
You  may want to try the specific version of `go 1.15`?

**Comment by kennytm** [comment]
`string(int)` is now a [vet error](https://golang.google.cn/doc/go1.15#vet) in Go 1.15. better just change that line 

https://github.com/pingcap/go-randgen/blob/1466757857eb85b0a78cdf888e6a9cd6a8758867/gendata/generators/letter.go#L7

into 

```go
return fmt.Sprintf("'%c'", randInRange('a', 'z'))
```
