### ISSUE TITLE
[Proposal] Add Support for PostgreSQL

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap/go-randgen#32]
I want to use this tool to test `PostgreSQL` compatible databases.

- [x]  Support `PostgreSQL` _syntax_
- [x]  Support to _connect_ to the database
- [x]  Support to _run_ the generated queries
- [x]  Provide an example `yy` file

I will submit a PR to implement this feature.

**Comment by cyliu0** [comment]
> I will submit a PR to implement this feature.

Cool!

**Comment by zhangysh1995** [comment]
I'm working on this proposal now. Hopefully, I will submit a PR soon.
